sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: oiv8HWJOQ3BRCBBuNczyoyKfPVqaxLJ/a+60iA8phvGZfXNTlblWzNqQZqvGZ+2voM16jSftvqIFc4hFlOhRokmNI/mpuzmvHrHrdnUG4XWOG7YzeT0qAvS5BqRfpzXMYW9KDVB0HXaVqKcqHSx/8oVazt63kwYnEr9TGcuAsEwcAO/q8N8ZTmbPNxmGetlIhavbtld0LfTKbSFBroV+yEe2haF2d4znPAjGbbfcmlnj15iNQ6htvxUQBIETUALA8N2JJ1nnPXO0L+ZiLQWaTaJ8k0pgrwapQAAX3qfVi0PrgWJaWlnh+hHscwSbMyw4mms0uWxd6Lf58xUcO9/A6t17vqtyhmddcQHgVa+iVyRTpY8hE9ifc6vZHIScb1ljH2cmYW+pf4Po9Gv03X/+aFfadtCQC5PFWXrf3Afr9KCmVxx+ttWovp+YXxjOMVW1Wawtheieqygph2CENRn5mRWskmUF+3yojaRQgyKQIUOkTExWaPhgf5C3YmRA1fP8z7c5y0Q6Ezd7POCAxaOtsOZ/SZ71xJTbvrP3rNWzd7dxfgUO1wUwScRF484frD8+TINBaXVk2OmE/NDdrv9Z3ZB+xGSSQJRoVAHzSqPx9JzCsVuFe6GiSFHXu9NLqgHSqWMFgo6+rHgzFcyUOaERujPjnaJ8ZvXwWvpCDCKftZk=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: eX+mTr+F/vCHCa0wMHM5opjU1g+njSW9ILYyhB1irDyV6NTUXOLDHF4SqMKMMjbcBkQmoyVjlqgjaN/U1lo/VlK6KVE5MrPWE6sUjWAssbjtP0E0LUTD/TGtRYkG6dz1yS99vuqctZn/H4HuuWruWW9fsjIUJXq4naaZs3Zu5GuW4a2OpVuxIi5b1s6C69xmWf8IoGf7+jvn3o7UjWCDiS5oeGHbQA+4lfkNRHzhQ+UHuA/jjbTRqMGadkeZWq+mKFR6l58iWMG8Mb2t5Wj9MrG4cWDk2s5cyIGPbKNPPxrAsHFmBRY7yUq0BZ0W0SdZlqGcwwmyEMnK5H3ysBghUz2nrQFzQySmFiKPUjHY/ApKSSpa/qwpBJ4e05kD0zoSmUwXteIMPPPJXmxB1DOxB9Zp2oRppna8WtepypO0/hhTcZPTmQnpVYr7/2qi61RNYfW/ehxBpTGU9epuHwf/AUjA+wcKDbPn8d1d0bqBSkDLpPp6bPdrZ9rcwzumG+gro+gt4Ctdr14QI+L8RkfJGxUKTljn+NbR0rXA/BstRn8iiZ9SjZh77tT8oToHYFrztdUtc7vuD/76XiKZgaUO19ekHEfwuJgu9NmNBtosmWCAsKh4U97NHsFckWncSFk5h+Lhk+byAPXdlNJcH5P7U25XufsfQv+uqt+upVnsOkk=
